url: "" # the base hostname & protocol for your site, e.g. https://example.com

permalink: pretty
template_engine: liquid

# Other options you might want to investigate:
#
base_path: "/my-portfolio"


# timezone: America/Los_Angeles
# pagination:
#   enabled: true
