url: "https://isaaclvs.github.io"

permalink: pretty
template_engine: liquid

# Other options you might want to investigate:
#
# base_path: "/"


# timezone: America/Los_Angeles
# pagination:
#   enabled: true
