name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn install
          bundle lock --add-platform x86_64-linux
          bundle install

      - name: Build with Bridgetown
        env:
          BRIDGETOWN_ENV: production
        run: |
          bin/bridgetown deploy
          ls -R ./output  # Verifica se os arquivos foram gerados

      - name: Upload build artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
