name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Atualizado para 3.2 ou superior
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn install
          bundle lock --add-platform x86_64-linux  # Corrige o problema de plataforma
          bundle install

      - name: Build with Bridgetown
        env:
          BRIDGETOWN_ENV: production
        run: |
          bin/bridgetown deploy
          ls -R ./output

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bridgetown-output
          path: ./output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bridgetown-output
          path: ./output
      - uses: actions/deploy-pages@v2